/**
 * Turns a restored SessionWindow back into live tabs. Ported from
 * chromium-reference/chrome/browser/sessions/session_restore.cc
 * (SessionRestoreImpl::RestoreTabsToBrowser / RestoreTab).
 *
 * Restore order mirrors Chrome: tabs are created in visual order with their
 * pinned state (AddRestoredTab), groups are formed and given their visual
 * data afterwards (RestoreTabGroupMetadata), then the selected tab is
 * activated. Group ids are re-generated by the model — exactly like Chrome,
 * which relabels every restored group via TabGroupId::GenerateNew() to avoid
 * cross-session id collisions — so callers get a groupIdMap back.
 */

import type { TabStripModel } from '../core/tab-strip-model'
import { AddTabFlags, type Tab, type TabGroupId, type TabId } from '../core/types'
import type { SessionTab, SessionWindow } from './session-types'

export interface RestoreOptions<T> {
  /**
   * Builds the live data payload for a restored tab. Defaults to the
   * persisted `data` value as-is. Tabs persisted with navigation tracking
   * only can derive their payload from currentNavigationEntry(tab).
   */
  createTabData?: (tab: SessionTab) => T
  /**
   * Keep the persisted tab ids (default). Ids already present in the model
   * fall back to generated ones. Pass false to always generate fresh ids —
   * Chrome's behavior, where restored tabs get new SessionIDs.
   */
  preserveTabIds?: boolean
  /**
   * Restore non-selected tabs in the discarded state, the analog of Chrome's
   * deferred TabLoader (background tabs exist but don't load until first
   * activation). Default false: everything restores loaded.
   */
  deferLoading?: boolean
}

export interface RestoreResult {
  tabsRestored: number
  /** Persisted tab id -> live tab id. Identity unless ids were regenerated. */
  tabIdMap: Map<TabId, TabId>
  /** Persisted group id -> live group id (always regenerated by the model). */
  groupIdMap: Map<TabGroupId, TabGroupId>
}

/**
 * Appends a SessionWindow's tabs to `model`. The model is typically empty;
 * with existing tabs the restored ones are appended after them (Chrome
 * restores into an existing browser the same way, session_restore.cc's
 * initial_tab_count handling).
 */
export function restoreSessionWindow<T>(
  model: TabStripModel<T>,
  window: SessionWindow,
  options: RestoreOptions<T> = {},
): RestoreResult {
  const createTabData = options.createTabData ?? ((tab: SessionTab) => tab.data as T)
  const preserveIds = options.preserveTabIds !== false

  const tabIdMap = new Map<TabId, TabId>()
  const groupIdMap = new Map<TabGroupId, TabGroupId>()
  const liveTabs: Tab<T>[] = []

  // RestoreTab (session_restore.cc): create tabs in stored visual order.
  // Saved order is pinned-first, so appending keeps pinned clamping happy.
  for (const sessionTab of window.tabs) {
    const id = preserveIds && model.getTabById(sessionTab.tabId) === null ? sessionTab.tabId : undefined
    const tab = model.insertTabAt(model.count, createTabData(sessionTab), {
      ...(id !== undefined ? { id } : {}),
      flags: sessionTab.pinned ? AddTabFlags.PINNED : AddTabFlags.NONE,
    })
    liveTabs.push(tab)
    tabIdMap.set(sessionTab.tabId, tab.id)
  }

  // RestoreTabGroupMetadata: form groups after all tabs are placed.
  if (model.supportsTabGroups) {
    for (const sessionGroup of window.tabGroups) {
      const indices: number[] = []
      window.tabs.forEach((sessionTab, i) => {
        if (sessionTab.groupId === sessionGroup.groupId) indices.push(model.indexOfTab(liveTabs[i]!))
      })
      if (indices.length === 0) continue
      const liveGroupId = model.addToNewGroup(indices, sessionGroup.visualData)
      groupIdMap.set(sessionGroup.groupId, liveGroupId)
    }
  }

  // ShowBrowser analog: activate the selected tab (already remapped to an
  // array position by restoreSessionFromCommands).
  if (liveTabs.length > 0) {
    const selected = Math.max(0, Math.min(window.selectedTabIndex, liveTabs.length - 1))
    model.activateTabAt(model.indexOfTab(liveTabs[selected]!))

    if (options.deferLoading) {
      for (let i = 0; i < liveTabs.length; i++) {
        if (i === selected) continue
        model.discardTabAt(model.indexOfTab(liveTabs[i]!))
      }
    }
  }

  return { tabsRestored: liveTabs.length, tabIdMap, groupIdMap }
}
